controller_manager:
  ros_parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

forward_position_controller:
  ros__parameters:
    joints:
      - c1_jt
      - f1_jt
      - t1_jt
      - c2_jt
      - f2_jt
      - t2_jt
      - c3_jt
      - f3_jt
      - t3_jt
      - c4_jt
      - f4_jt
      - t4_jt
      - c5_jt
      - f5_jt
      - t5_jt
      - c6_jt
      - f6_jt
      - t6_jt