controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0

joint_trajectory_controller:
  ros__parameters:
    joints:
      - c1_jt
      - f1_jt
      - t1_jt
      - c2_jt
      - f2_jt
      - t2_jt
      - c3_jt
      - f3_jt
      - t3_jt
      - c4_jt
      - f4_jt
      - t4_jt
      - c5_jt
      - f5_jt
      - t5_jt
      - c6_jt
      - f6_jt
      - t6_jt

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0